if(WIN32)
    set(CMAKE_EXECUTABLE_SUFFIX ".exe")
endif()

# Make sure the path is normalized into the cmake stadard.
cmake_path(SET NORMALIZED_COMPILER_PATH "${COMPILER_PATH}")

set(CMAKE_AR           ${NORMALIZED_COMPILER_PATH}/ar${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")  
set(CMAKE_C_COMPILER   ${NORMALIZED_COMPILER_PATH}/gcc${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_CXX_COMPILER ${NORMALIZED_COMPILER_PATH}/g++${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_LINKER       ${NORMALIZED_COMPILER_PATH}/ld${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_OBJCOPY      ${NORMALIZED_COMPILER_PATH}/objcopy${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_RANLIB       ${NORMALIZED_COMPILER_PATH}/ranlib${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_SIZE         ${NORMALIZED_COMPILER_PATH}/size${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
set(CMAKE_STRIP        ${NORMALIZED_COMPILER_PATH}/strip${CMAKE_EXECUTABLE_SUFFIX} CACHE INTERNAL "")
